[package]
name = "lensy"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.9", features = ["runtime-tokio", "sqlite", "migrate"] }
image = { version = "0.25", default-features = false, features = [
  "jpeg",
  "png",
  "webp",
] }
blake3 = "1"
thiserror = "2"
uuid = { version = "1", features = ["v4"] }
tracing = "0.1"
