// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package repo

import (
	"context"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (
  name, token_prefix, token_hash, created_at, expires_at
) VALUES (?, ?, ?, ?, ?)
RETURNING id, name, token_prefix, token_hash, created_at, last_used_at, expires_at, revoked_at
`

type CreateAPITokenParams struct {
	Name        string `json:"name"`
	TokenPrefix string `json:"token_prefix"`
	TokenHash   string `json:"token_hash"`
	CreatedAt   int64  `json:"created_at"`
	ExpiresAt   *int64 `json:"expires_at"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, createAPIToken,
		arg.Name,
		arg.TokenPrefix,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, name, token_prefix, token_hash, created_at, last_used_at, expires_at, revoked_at FROM api_tokens
WHERE token_hash = ?
LIMIT 1
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, name, token_prefix, token_hash, created_at, last_used_at, expires_at, revoked_at FROM api_tokens
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAPITokens(ctx context.Context) ([]ApiToken, error) {
	rows, err := q.db.QueryContext(ctx, listAPITokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiToken
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenPrefix,
			&i.TokenHash,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :execrows
UPDATE api_tokens
SET revoked_at = ?
WHERE id = ? AND revoked_at IS NULL
`

type RevokeAPITokenParams struct {
	RevokedAt *int64 `json:"revoked_at"`
	ID        int64  `json:"id"`
}

func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAPIToken, arg.RevokedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchAPIToken = `-- name: TouchAPIToken :execrows
UPDATE api_tokens
SET last_used_at = ?
WHERE id = ?
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > ?)
`

type TouchAPITokenParams struct {
	LastUsedAt *int64 `json:"last_used_at"`
	ID         int64  `json:"id"`
	ExpiresAt  *int64 `json:"expires_at"`
}

func (q *Queries) TouchAPIToken(ctx context.Context, arg TouchAPITokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchAPIToken, arg.LastUsedAt, arg.ID, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
