// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: images.sql

package repo

import (
	"context"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images (
  public_id, storage_key, thumbnail_key,
  original_name,
  stored_size, thumbnail_size,
  width, height, thumbnail_width, thumbnail_height,
  content_hash, pixel_hash,
  created_at, updated_at
) VALUES (
  ?, ?, ?,
  ?,
  ?, ?,
  ?, ?, ?, ?,
  ?, ?,
  ?, ?
)
RETURNING id, public_id, storage_key, thumbnail_key, original_name, stored_size, thumbnail_size, width, height, thumbnail_width, thumbnail_height, content_hash, pixel_hash, created_at, updated_at, deleted_at
`

type CreateImageParams struct {
	PublicID        string `json:"public_id"`
	StorageKey      string `json:"storage_key"`
	ThumbnailKey    string `json:"thumbnail_key"`
	OriginalName    string `json:"original_name"`
	StoredSize      int64  `json:"stored_size"`
	ThumbnailSize   int64  `json:"thumbnail_size"`
	Width           int64  `json:"width"`
	Height          int64  `json:"height"`
	ThumbnailWidth  int64  `json:"thumbnail_width"`
	ThumbnailHeight int64  `json:"thumbnail_height"`
	ContentHash     string `json:"content_hash"`
	PixelHash       string `json:"pixel_hash"`
	CreatedAt       int64  `json:"created_at"`
	UpdatedAt       int64  `json:"updated_at"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, createImage,
		arg.PublicID,
		arg.StorageKey,
		arg.ThumbnailKey,
		arg.OriginalName,
		arg.StoredSize,
		arg.ThumbnailSize,
		arg.Width,
		arg.Height,
		arg.ThumbnailWidth,
		arg.ThumbnailHeight,
		arg.ContentHash,
		arg.PixelHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.StorageKey,
		&i.ThumbnailKey,
		&i.OriginalName,
		&i.StoredSize,
		&i.ThumbnailSize,
		&i.Width,
		&i.Height,
		&i.ThumbnailWidth,
		&i.ThumbnailHeight,
		&i.ContentHash,
		&i.PixelHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteImagePermanently = `-- name: DeleteImagePermanently :one
DELETE FROM images
WHERE public_id = ? AND deleted_at IS NOT NULL
RETURNING id, public_id, storage_key, thumbnail_key, original_name, stored_size, thumbnail_size, width, height, thumbnail_width, thumbnail_height, content_hash, pixel_hash, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteImagePermanently(ctx context.Context, publicID string) (Image, error) {
	row := q.db.QueryRowContext(ctx, deleteImagePermanently, publicID)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.StorageKey,
		&i.ThumbnailKey,
		&i.OriginalName,
		&i.StoredSize,
		&i.ThumbnailSize,
		&i.Width,
		&i.Height,
		&i.ThumbnailWidth,
		&i.ThumbnailHeight,
		&i.ContentHash,
		&i.PixelHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveImageByPixelHash = `-- name: GetActiveImageByPixelHash :one
SELECT id, public_id, storage_key, thumbnail_key, original_name, stored_size, thumbnail_size, width, height, thumbnail_width, thumbnail_height, content_hash, pixel_hash, created_at, updated_at, deleted_at FROM images
WHERE pixel_hash = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetActiveImageByPixelHash(ctx context.Context, pixelHash string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getActiveImageByPixelHash, pixelHash)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.StorageKey,
		&i.ThumbnailKey,
		&i.OriginalName,
		&i.StoredSize,
		&i.ThumbnailSize,
		&i.Width,
		&i.Height,
		&i.ThumbnailWidth,
		&i.ThumbnailHeight,
		&i.ContentHash,
		&i.PixelHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveImageByPublicID = `-- name: GetActiveImageByPublicID :one
SELECT id, public_id, storage_key, thumbnail_key, original_name, stored_size, thumbnail_size, width, height, thumbnail_width, thumbnail_height, content_hash, pixel_hash, created_at, updated_at, deleted_at FROM images
WHERE public_id = ? AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetActiveImageByPublicID(ctx context.Context, publicID string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getActiveImageByPublicID, publicID)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.StorageKey,
		&i.ThumbnailKey,
		&i.OriginalName,
		&i.StoredSize,
		&i.ThumbnailSize,
		&i.Width,
		&i.Height,
		&i.ThumbnailWidth,
		&i.ThumbnailHeight,
		&i.ContentHash,
		&i.PixelHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDeletedImageByPublicID = `-- name: GetDeletedImageByPublicID :one
SELECT id, public_id, storage_key, thumbnail_key, original_name, stored_size, thumbnail_size, width, height, thumbnail_width, thumbnail_height, content_hash, pixel_hash, created_at, updated_at, deleted_at FROM images
WHERE public_id = ? AND deleted_at IS NOT NULL
LIMIT 1
`

func (q *Queries) GetDeletedImageByPublicID(ctx context.Context, publicID string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getDeletedImageByPublicID, publicID)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.StorageKey,
		&i.ThumbnailKey,
		&i.OriginalName,
		&i.StoredSize,
		&i.ThumbnailSize,
		&i.Width,
		&i.Height,
		&i.ThumbnailWidth,
		&i.ThumbnailHeight,
		&i.ContentHash,
		&i.PixelHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveImages = `-- name: ListActiveImages :many
SELECT id, public_id, storage_key, thumbnail_key, original_name, stored_size, thumbnail_size, width, height, thumbnail_width, thumbnail_height, content_hash, pixel_hash, created_at, updated_at, deleted_at FROM images
WHERE deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT ?
`

func (q *Queries) ListActiveImages(ctx context.Context, limit int64) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listActiveImages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.StorageKey,
			&i.ThumbnailKey,
			&i.OriginalName,
			&i.StoredSize,
			&i.ThumbnailSize,
			&i.Width,
			&i.Height,
			&i.ThumbnailWidth,
			&i.ThumbnailHeight,
			&i.ContentHash,
			&i.PixelHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveImagesAfter = `-- name: ListActiveImagesAfter :many
SELECT id, public_id, storage_key, thumbnail_key, original_name, stored_size, thumbnail_size, width, height, thumbnail_width, thumbnail_height, content_hash, pixel_hash, created_at, updated_at, deleted_at FROM images
WHERE deleted_at IS NULL
  AND (created_at < ? OR (created_at = ? AND id < ?))
ORDER BY created_at DESC, id DESC
LIMIT ?
`

type ListActiveImagesAfterParams struct {
	CreatedAt   int64 `json:"created_at"`
	CreatedAt_2 int64 `json:"created_at_2"`
	ID          int64 `json:"id"`
	Limit       int64 `json:"limit"`
}

func (q *Queries) ListActiveImagesAfter(ctx context.Context, arg ListActiveImagesAfterParams) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listActiveImagesAfter,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.StorageKey,
			&i.ThumbnailKey,
			&i.OriginalName,
			&i.StoredSize,
			&i.ThumbnailSize,
			&i.Width,
			&i.Height,
			&i.ThumbnailWidth,
			&i.ThumbnailHeight,
			&i.ContentHash,
			&i.PixelHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedImages = `-- name: ListDeletedImages :many
SELECT id, public_id, storage_key, thumbnail_key, original_name, stored_size, thumbnail_size, width, height, thumbnail_width, thumbnail_height, content_hash, pixel_hash, created_at, updated_at, deleted_at FROM images
WHERE deleted_at IS NOT NULL
ORDER BY deleted_at DESC, id DESC
LIMIT ?
`

func (q *Queries) ListDeletedImages(ctx context.Context, limit int64) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listDeletedImages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.StorageKey,
			&i.ThumbnailKey,
			&i.OriginalName,
			&i.StoredSize,
			&i.ThumbnailSize,
			&i.Width,
			&i.Height,
			&i.ThumbnailWidth,
			&i.ThumbnailHeight,
			&i.ContentHash,
			&i.PixelHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedImagesAfter = `-- name: ListDeletedImagesAfter :many
SELECT id, public_id, storage_key, thumbnail_key, original_name, stored_size, thumbnail_size, width, height, thumbnail_width, thumbnail_height, content_hash, pixel_hash, created_at, updated_at, deleted_at FROM images
WHERE deleted_at IS NOT NULL
  AND (deleted_at < ? OR (deleted_at = ? AND id < ?))
ORDER BY deleted_at DESC, id DESC
LIMIT ?
`

type ListDeletedImagesAfterParams struct {
	DeletedAt   *int64 `json:"deleted_at"`
	DeletedAt_2 *int64 `json:"deleted_at_2"`
	ID          int64  `json:"id"`
	Limit       int64  `json:"limit"`
}

func (q *Queries) ListDeletedImagesAfter(ctx context.Context, arg ListDeletedImagesAfterParams) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listDeletedImagesAfter,
		arg.DeletedAt,
		arg.DeletedAt_2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.StorageKey,
			&i.ThumbnailKey,
			&i.OriginalName,
			&i.StoredSize,
			&i.ThumbnailSize,
			&i.Width,
			&i.Height,
			&i.ThumbnailWidth,
			&i.ThumbnailHeight,
			&i.ContentHash,
			&i.PixelHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreImage = `-- name: RestoreImage :execrows
UPDATE images
SET deleted_at = NULL, updated_at = ?
WHERE public_id = ? AND deleted_at IS NOT NULL
`

type RestoreImageParams struct {
	UpdatedAt int64  `json:"updated_at"`
	PublicID  string `json:"public_id"`
}

func (q *Queries) RestoreImage(ctx context.Context, arg RestoreImageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, restoreImage, arg.UpdatedAt, arg.PublicID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteImage = `-- name: SoftDeleteImage :execrows
UPDATE images
SET deleted_at = ?, updated_at = ?
WHERE public_id = ? AND deleted_at IS NULL
`

type SoftDeleteImageParams struct {
	DeletedAt *int64 `json:"deleted_at"`
	UpdatedAt int64  `json:"updated_at"`
	PublicID  string `json:"public_id"`
}

func (q *Queries) SoftDeleteImage(ctx context.Context, arg SoftDeleteImageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteImage, arg.DeletedAt, arg.UpdatedAt, arg.PublicID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
