// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

type ApiToken struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	TokenPrefix string `json:"token_prefix"`
	TokenHash   string `json:"token_hash"`
	CreatedAt   int64  `json:"created_at"`
	LastUsedAt  *int64 `json:"last_used_at"`
	ExpiresAt   *int64 `json:"expires_at"`
	RevokedAt   *int64 `json:"revoked_at"`
}

type Image struct {
	ID              int64  `json:"id"`
	PublicID        string `json:"public_id"`
	StorageKey      string `json:"storage_key"`
	ThumbnailKey    string `json:"thumbnail_key"`
	OriginalName    string `json:"original_name"`
	StoredSize      int64  `json:"stored_size"`
	ThumbnailSize   int64  `json:"thumbnail_size"`
	Width           int64  `json:"width"`
	Height          int64  `json:"height"`
	ThumbnailWidth  int64  `json:"thumbnail_width"`
	ThumbnailHeight int64  `json:"thumbnail_height"`
	ContentHash     string `json:"content_hash"`
	PixelHash       string `json:"pixel_hash"`
	CreatedAt       int64  `json:"created_at"`
	UpdatedAt       int64  `json:"updated_at"`
	DeletedAt       *int64 `json:"deleted_at"`
}

type User struct {
	ID           int64  `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
	LastLoginAt  *int64 `json:"last_login_at"`
	DisabledAt   *int64 `json:"disabled_at"`
}
